source 'https://github.com/CocoaPods/Specs.git'
target 'ReachIn' do
 use_frameworks!
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'Alamofire', '~> 5.0.0-beta.5'
pod 'SwiftyJSON', '~> 4.0'
end

